stages:
  - test
  - build
  - release

image: rust:latest

cache:
  paths:
    - target/
    - ~/.cargo/

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  CARGO_TEST_VERBOSITY: ""
  RUST_TARGET_DIR: "${CI_PROJECT_DIR}/target" # Define target directory for caching
  RUST_BACKTRACE: 1
  TARGETS: "x86_64-unknown-linux-gnu aarch64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin x86_64-pc-windows-msvc"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/registry  # Caches downloaded dependencies
    - .cargo/git       # Caches cloned dependencies
    - target           # Caches build artifacts

test:
  stage: test
  script:
    - cargo test ${CARGO_TEST_VERBOSITY}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG

# Build job that creates release artifacts
build:
  stage: build
  needs:
    - test
  script:
    - chmod +x build.sh
    - ./build.sh
  artifacts:
    paths:
      - dist/korrect-*.tar.gz
      - dist/korrect-*.sha256
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG

# Release job that creates a GitLab release
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" \
        --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"korrect-x86_64-linux.tar.gz\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/korrect-x86_64-linux.tar.gz\"}" \
        --assets-link "{\"name\":\"korrect-aarch64-linux.tar.gz\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/korrect-aarch64-linux.tar.gz\"}" \
        --assets-link "{\"name\":\"korrect-x86_64-linux.tar.gz.sha256\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/korrect-x86_64-linux.tar.gz.sha256\"}" \
        --assets-link "{\"name\":\"korrect-aarch64-linux.tar.gz.sha256\",\"url\":\"${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/korrect-aarch64-linux.tar.gz.sha256\"}"
  rules:
    - if: $CI_COMMIT_TAG    # Only run on tags

# Optional: Build and publish Docker image
docker:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  needs:
    - build
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_TAG    # Only run on tags
