[package]
name = "mockk8sserver"
version = "0.1.0"
authors = ["dan@badpacket.in"]
edition = "2021"
description = "A mock kubectl download server."

[dependencies]
actix-web = "4.4"
clap = { version = "4.4", features = ["derive"] }
